[project]
name = "scribeflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "app>=0.0.1",
    "pytest>=9.0.2",
    "python-multipart>=0.0.21",
]
